language: node_js
services: docker

script:
  - docker version
  - docker images
  - npm install -g rebase-docker-image
  - rebase-docker-image -h
git:
  depth: 1
language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw
